# Generated by Django 4.2.7 on 2024-01-22 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('photo', models.ImageField(upload_to='media/')),
                ('count_view', models.IntegerField(default=0)),
                ('date_publication', models.DateField(default=datetime.date(2024, 1, 22))),
            ],
        ),
    ]
